import { AiModelMetadata } from "./types.js";

export const MODEL_REGISTRY: Record<string, AiModelMetadata> = {
  "moonshotai/kimi-k3-free": {
    id: "moonshotai/kimi-k3-free",
    name: "Kimi K3 Free",
    provider: "TokenRouter",
    contextLength: 128000,
    supportsVision: false,
    supportsToolCalling: true,
    supportsStreaming: true,
    supportsJson: true,
    costPer1kInputTokens: 0.0,
    costPer1kOutputTokens: 0.0,
  },
  "gpt-4o": {
    id: "gpt-4o",
    name: "GPT-4 Omni",
    provider: "OpenAI",
    contextLength: 128000,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStreaming: true,
    supportsJson: true,
    costPer1kInputTokens: 0.005,
    costPer1kOutputTokens: 0.015,
  },
  "claude-3-5-sonnet": {
    id: "claude-3-5-sonnet",
    name: "Claude 3.5 Sonnet",
    provider: "Anthropic",
    contextLength: 200000,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStreaming: true,
    supportsJson: true,
    costPer1kInputTokens: 0.003,
    costPer1kOutputTokens: 0.015,
  },
  "gemini-1.5-pro": {
    id: "gemini-1.5-pro",
    name: "Gemini 1.5 Pro",
    provider: "Google Gemini",
    contextLength: 1000000,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStreaming: true,
    supportsJson: true,
    costPer1kInputTokens: 0.0035,
    costPer1kOutputTokens: 0.0105,
  },
  "llama3": {
    id: "llama3",
    name: "Llama 3 8B Local",
    provider: "Ollama",
    contextLength: 8192,
    supportsVision: false,
    supportsToolCalling: false,
    supportsStreaming: true,
    supportsJson: true,
    costPer1kInputTokens: 0.0,
    costPer1kOutputTokens: 0.0,
  },
  "mock-model": {
    id: "mock-model",
    name: "Mock Provider Model",
    provider: "Mock",
    contextLength: 32768,
    supportsVision: true,
    supportsToolCalling: true,
    supportsStreaming: true,
    supportsJson: true,
    costPer1kInputTokens: 0.0,
    costPer1kOutputTokens: 0.0,
  },
};
